# Character ID mappings
mappings = {
    0: "Mario",
    1: "Luigi",
    2: "DK",
    3: "Diddy",
    4: "Peach",
    5: "Daisy",
    6: "Yoshi",
    7: "Baby Mario",
    8: "Baby Luigi",
    9: "Bowser",
    10: "Wario",
    11: "Waluigi",
    12: "Koopa(G)",
    13: "Toad(R)",
    14: "Boo",
    15: "Toadette",
    16: "Shy Guy(R)",
    17: "Birdo",
    18: "Monty",
    19: "Bowser Jr",
    20: "Paratroopa(R)",
    21: "Pianta(B)",
    22: "Pianta(R)",
    23: "Pianta(Y)",
    24: "Noki(B)",
    25: "Noki(R)",
    26: "Noki(G)",
    27: "Bro(H)",
    28: "Toadsworth",
    29: "Toad(B)",
    30: "Toad(Y)",
    31: "Toad(G)",
    32: "Toad(P)",
    33: "Magikoopa(B)",
    34: "Magikoopa(R)",
    35: "Magikoopa(G)",
    36: "Magikoopa(Y)",
    37: "King Boo",
    38: "Petey",
    39: "Dixie",
    40: "Goomba",
    41: "Paragoomba",
    42: "Koopa(R)",
    43: "Paratroopa(G)",
    44: "Shy Guy(B)",
    45: "Shy Guy(Y)",
    46: "Shy Guy(G)",
    47: "Shy Guy(Bk)",
    48: "Dry Bones(Gy)",
    49: "Dry Bones(G)",
    50: "Dry Bones(R)",
    51: "Dry Bones(B)",
    52: "Bro(F)",
    53: "Bro(B)",
    None: "None"
}

# Flip dictionary
reverse_mappings = dict((v, k) for k, v in mappings.items())

# dict of character aliases and corresponding character ID
aliases = {
    "mario": 0,
    "mar": 0,
    "luigi": 1,
    "weegee": 1,
    "lu": 1,
    "dk": 2,
    "donkeykong": 2,
    "diddy": 3,
    "diddykong": 3,
    "peach": 4,
    "daisy": 5,
    "yoshi": 6,
    "yosh": 6,
    "babymario": 7,
    "bmario": 7,
    "bluigi": 8,
    "babyluigi": 8,
    "bowser": 9,
    "bow": 9,
    "wario": 10,
    "waluigi": 11,
    "walu": 11,
    "koopa(g)": 12,
    "gkoopa": 12,
    "greenkoopa": 12,
    "greenkoopatroopa": 12,
    "greg": 12,
    "toad(r)": 13,
    "rtoad": 13,
    "toadred": 13,
    "redtoad": 13,
    "toad": 13,
    "boo": 14,
    "toadette": 15,
    "tdette": 15,
    "shyguy(r)": 16,
    "shyguyred": 16,
    "redshyguy": 16,
    "redguy": 16,
    "rsg": 16,
    "shyguy": 16,
    "birdo": 17,
    "monty": 18,
    "montymole": 18,
    "moonball": 18,
    "bowser jr": 19,
    "bj": 19,
    "bowserjunior": 19,
    "jr": 19,
    "paratroopa(r)": 20,
    "koopaparatroopared": 20,
    "redkoopaparatroopa": 20,
    "parared": 20,
    "redpara": 20,
    "rpara": 20,
    "ptred": 20,
    "redpt": 20,
    "pianta(b)": 21,
    "piantablue": 21,
    "bluepianta": 21,
    "blueblob": 21,
    "bb": 21,
    "pianta(r)": 22,
    "piantared": 22,
    "redpianta": 22,
    "pm": 22,
    "pianta(y)": 23,
    "piantayellow": 23,
    "yellowpianta": 23,
    "yellafella": 23,
    "yellowfellow": 23,
    "yf": 23,
    "noki(b)": 24,
    "nokiblue": 24,
    "bluenoki": 24,
    "boki": 24,
    "bnoki": 24,
    "bnoke": 24,
    "noki(r)": 25,
    "nokired": 25,
    "rednoki": 25,
    "gnoki": 26,
    "noki(g)": 26,
    "nokigreen": 26,
    "greennoki": 26,
    "mintnoki": 26,
    "gnoke": 26,
    "gnocchi": 26,
    "bro(h)": 27,
    "hammerbro": 27,
    "hammer": 27,
    "h!bro": 27,
    "hbro": 27,
    "toadsworth": 28,
    "tw": 28,
    "peterose": 28,
    "oldman": 28,
    "toad(b)": 29,
    "toadblue": 29,
    "bluetoad": 29,
    "btoad": 29,
    "teardrop": 29,
    "toad(y)": 30,
    "toadyellow": 30,
    "yellowtoad": 30,
    "peetoad": 30,
    "cornpop": 30,
    "toad(g)": 31,
    "toadgreen": 31,
    "greentoad": 31,
    "gtoad": 31,
    "toad(p)": 32,
    "toadpurple": 32,
    "purpletoad": 32,
    "leantoad": 32,
    "ptoad": 32,
    "magikoopa(b)": 33,
    "magikoopablue": 33,
    "bluemagikoopa": 33,
    "magblue": 33,
    "bluemag": 33,
    "mageblue": 33,
    "bluemage": 33,
    "bmage": 33,
    "bmag": 33,
    "magikoopa(r)": 34,
    "magikoopared": 34,
    "redmagikoopa": 34,
    "magred": 34,
    "redmag": 34,
    "magered": 34,
    "redmage": 34,
    "rmag": 34,
    "rmage": 34,
    "magikoopa(g)": 35,
    "magikoopagreen": 35,
    "greenmagikoopa": 35,
    "maggreen": 35,
    "greenmag": 35,
    "magegreen": 35,
    "greenmage": 35,
    "gmag": 35,
    "gmage": 35,
    "magikoopa(y)": 36,
    "magikoopayellow": 36,
    "yellowmagikoopa": 36,
    "magyellow": 36,
    "yellowmag": 36,
    "mageyellow": 36,
    "yellowmage": 36,
    "pisswizard": 36,
    "pisswizz": 36,
    "pizzwizz": 36,
    "weezard": 36,
    "ymag": 36,
    "kingboo": 37,
    "kboo": 37,
    "kb": 37,
    "peteypiranha": 38,
    "petey": 38,
    "peaty": 38,
    "peety": 38,
    "peter": 38,
    "dixiekong": 39,
    "dixie": 39,
    "goomba": 40,
    "goombo": 40,
    "dingus": 40,
    "paragoomba": 41,
    "wingombo": 41,
    "parag": 41,
    "pg": 41,
    "koopa(r)": 42,
    "koopa": 42,
    "koopatroopa": 42,
    "redkoopa": 42,
    "redkoopatroopa": 42,
    "koopared": 42,
    "koopatroopared": 42,
    "rkoopa": 42,
    "rafa": 42,
    "rafael": 42,
    "ron": 42,
    "ronald": 42,
    "paratroopa(g)": 43,
    "koopaparatroopagreen": 43,
    "greenkoopaparatroopa": 43,
    "paragreen": 43,
    "greenpara": 43,
    "ptgreen": 43,
    "greenpt": 43,
    "para": 43,
    "parat": 43,
    "pt": 43,
    "gpara": 43,
    "shyguy(b)": 44,
    "shyguyblue": 44,
    "blueshyguy": 44,
    "blueguy": 44,
    "bsg": 44,
    "bshyguy": 44,
    "shyguy(y)": 45,
    "shyguyyellow": 45,
    "blueshyyellow": 45,
    "yellowguy": 45,
    "ysg": 45,
    "yshyguy": 45,
    "shyguy(g)": 46,
    "shyguygreen": 46,
    "greenshyguy": 46,
    "greenguy": 46,
    "gsg": 46,
    "gshyguy": 46,
    "shyguy(bk)": 47,
    "shyguyblack": 47,
    "blackshyguy": 47,
    "blackguy": 47,
    "blsg": 47,
    "blshyguy": 47,
    "drybones(gy)": 48,
    "drybones": 48,
    "bones": 48,
    "drybonesgray": 48,
    "drybonesgrey": 48,
    "greydrybones": 48,
    "graydrybones": 48,
    "bonesgray": 48,
    "bonesgrey": 48,
    "greybones": 48,
    "graybones": 48,
    "barebones": 48,
    "drybones(g)": 49,
    "drybonesgreen": 49,
    "greendrybones": 49,
    "bonesgreen": 49,
    "greenbones": 49,
    "gbones": 49,
    "drybones(r)": 50,
    "drybonesred": 50,
    "reddrybones": 50,
    "bonesred": 50,
    "redbones": 50,
    "rbones": 50,
    "drybones(b)": 51,
    "drybonesblue": 51,
    "bluedrybones": 51,
    "bonesblue": 51,
    "bluebones": 51,
    "bbones": 51,
    "bro(f)": 52,
    "fire": 52,
    "firebro": 52,
    "f!bro": 52,
    "fbro": 52,
    "bro(b)": 53,
    "boomerbro": 53,
    "boomer": 53,
    "b!bro": 53,
    "bbro": 53
}

images = {
    "Mario": "https://i.imgur.com/gX96BkX.png",
    "Luigi": "https://i.imgur.com/Kxl1w4E.png",
    "DK": "https://i.imgur.com/wjganx4.png",
    "Diddy": "https://i.imgur.com/bQymTq0.png",
    "Peach": "https://i.imgur.com/eKWczoD.png",
    "Daisy": "https://i.imgur.com/4LX9GyT.png",
    "Yoshi": "https://i.imgur.com/RD7wbpo.png",
    "Baby Mario": "https://i.imgur.com/f2Jtw0k.png",
    "Baby Luigi": "https://i.imgur.com/48Hg8Zz.png",
    "Bowser": "https://i.imgur.com/7vyo9MU.png",
    "Wario": "https://i.imgur.com/Sq4Osx1.png",
    "Waluigi": "https://i.imgur.com/XzV1Agh.png",
    "Koopa(G)": "https://i.imgur.com/X34PLib.png",
    "Toad(R)": "https://i.imgur.com/rx1dail.png",
    "Boo": "https://i.imgur.com/kyWOVDn.png",
    "Toadette": "https://i.imgur.com/mFIfYPC.png",
    "Shy Guy(R)": "https://i.imgur.com/uxAZFWt.png",
    "Birdo": "https://i.imgur.com/xAHfoQf.png",
    "Monty": "https://i.imgur.com/P4xJNkG.png",
    "Bowser Jr": "https://i.imgur.com/8rCQ6Lr.png",
    "Paratroopa(R)": "https://i.imgur.com/8Hazpxu.png",
    "Pianta(B)": "https://i.imgur.com/gCnt8o3.png",
    "Pianta(R)": "https://i.imgur.com/MNjbBkJ.png",
    "Pianta(Y)": "https://i.imgur.com/5vu46Gv.png",
    "Noki(B)": "https://i.imgur.com/thl3062.png",
    "Noki(R)": "https://i.imgur.com/QeXUsku.png",
    "Noki(G)": "https://i.imgur.com/0XQopid.png",
    "Bro(H)": "https://i.imgur.com/KObBwz5.png",
    "Toadsworth": "https://i.imgur.com/5jvnMSo.png",
    "Toad(B)": "https://i.imgur.com/G341tID.png",
    "Toad(Y)": "https://i.imgur.com/ll5dRWT.png",
    "Toad(G)": "https://i.imgur.com/n3pQwFA.png",
    "Toad(P)": "https://i.imgur.com/Qaq2G7F.png",
    "Magikoopa(B)": "https://i.imgur.com/soldxb3.png",
    "Magikoopa(R)": "https://i.imgur.com/HZHgF7U.png",
    "Magikoopa(G)": "https://i.imgur.com/RhFq2hJ.png",
    "Magikoopa(Y)": "https://i.imgur.com/SmGdX8j.png",
    "King Boo": "https://i.imgur.com/bB0Tbog.png",
    "Petey": "https://i.imgur.com/hnwO5xU.png",
    "Dixie": "https://i.imgur.com/6Rh9YDc.png",
    "Goomba": "https://i.imgur.com/CcCn7jX.png",
    "Paragoomba": "https://i.imgur.com/dhf4Gnn.png",
    "Koopa(R)": "https://i.imgur.com/MXISCHw.png",
    "Paratroopa(G)": "https://i.imgur.com/O24HeI1.png",
    "Shy Guy(B)": "https://i.imgur.com/Abna3bD.png",
    "Shy Guy(Y)": "https://i.imgur.com/LvISJzT.png",
    "Shy Guy(G)": "https://i.imgur.com/ZWzCaC8.png",
    "Shy Guy(Bk)": "https://i.imgur.com/fjz780N.png",
    "Dry Bones(Gy)": "https://i.imgur.com/nyrIEek.png",
    "Dry Bones(G)": "https://i.imgur.com/KtXTC8X.png",
    "Dry Bones(R)": "https://i.imgur.com/1qoWb4F.png",
    "Dry Bones(B)": "https://i.imgur.com/vJRutvp.png",
    "Bro(F)": "https://i.imgur.com/c0n64rJ.png",
    "Bro(B)": "https://i.imgur.com/9oBKUlT.png",
    "all": "https://i.imgur.com/yTjBaXK.png"
}
