name: Lint

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Ruff
        run: pip install -r requirements-dev.txt
      - name: Ruff check
        run: ruff check .
